# Generated by Django 5.2.17 on 2026-10-02 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0031_alter_courseoverview_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoverview',
            name='course_theme_variant',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='historicalcourseoverview',
            name='course_theme_variant',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
