# Generated by Django 5.2.11 on 2026-02-23 23:41

import opaque_keys.edx.django.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("modulestore_migrator", "0001_squashed_0007_switch_to_openedx_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modulestoreblocksource",
            name="key",
            field=opaque_keys.edx.django.models.UsageKeyField(
                case_sensitive=True,
                help_text="Original usage key of the XBlock that has been imported.",
                max_length=255,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="modulestoresource",
            name="key",
            field=opaque_keys.edx.django.models.LearningContextKeyField(
                case_sensitive=True,
                help_text="Key of the content source (a course or a legacy library)",
                max_length=255,
                unique=True,
            ),
        ),
    ]
